### PR TITLE
Fix SSE headers symbol error when Headers object is passed

### LINKED ISSUE #150: Fix SSE EventSource error for localhost HTTPS connections
## Problem

When connecting to a localhost HTTPS server using SSE transport, mcp-remote fails with the following error:

```
SseError: SSE error: undefined: Key Symbol(headers list) in undefined.headers is a symbol, 
which cannot be converted to a ByteString
```

This occurs specifically when:
- Connecting to `https://localhost/*` endpoints  
- Using self-signed certificates
- The SSE transport is used (either directly or as a fallback)

## Root Cause

The error happens because the EventSource API has issues processing the custom `fetch` function provided in `eventSourceInit` when dealing with localhost HTTPS URLs. The headers are being processed incorrectly, causing a Symbol to appear where a string is expected.

## Solution

The fix detects localhost HTTPS connections and uses a simplified `eventSourceInit` configuration that avoids the custom fetch function. For non-localhost connections, the original behavior is preserved.

The key change is in `src/lib/utils.ts` in the `connectToRemoteServer` function:
- Check if the URL is localhost (including 127.0.0.1 and ::1)
- For localhost HTTPS connections, use a simplified eventSourceInit without the custom fetch function
- For other connections, preserve the existing behavior with the custom fetch function

## Testing

Tested with a local Docker setup running an MCP server behind nginx with self-signed certificates. The fix allows successful connection where it previously failed consistently.

Environment:
- Node.js v21.4.0
- mcp-remote v0.1.27
- macOS with self-signed SSL certificates
- Docker containers with nginx proxy and MCP server

Before the fix: Consistent "Symbol(headers list)" error
After the fix: Successful connection using SSEClientTransport

### PR DESCRIPTION
**Pull request by geelen**
Handle Headers object properly in eventSourceInit fetch function by converting it to a plain object before spreading. This fixes the ByteString conversion error that occurs when Headers contains symbols.

Closes #150 and #148

### CODE REVIEW

File: src/lib/utils.ts [hunk 1]
```diff
@@ -14,7 +14,7 @@ import fs from 'fs'
 import { readFile, rm } from 'fs/promises'
 import path from 'path'
 import { version as MCP_REMOTE_VERSION } from '../../package.json'
-import { fetch, setGlobalDispatcher, RequestInit, EnvHttpProxyAgent } from 'undici'
+import { EnvHttpProxyAgent, fetch, Headers, RequestInit, setGlobalDispatcher } from 'undici'
```
Comment (rjurney) [inline src/lib/utils.ts:17]: @geelen Ah, much more elegant :)
